version: "3.9"

services:
  app1:
    build:
      context: .
      args:
        - APP=app1
    container_name: app1
    command: yarn workspace app1 run dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/app

  app2:
    build:
      context: .
      args:
        - APP=app2
    container_name: app2
    command: yarn workspace app2 run dev
    ports:
      - "3001:3001"
    volumes:
      - ./:/home/app

  logger:
    build:
      context: .
      args:
        - APP=logger
    container_name: logger_builder
    command: yarn workspace logger run build:watch
    volumes:
      - ./:/home/app
  middlewares-lib:
    build:
      context: .
      args:
        - APP=middlewares-lib
    container_name: middlewares_lib_builder
    command: yarn workspace middlewares-lib run build:watch
    volumes:
      - ./:/home/app